services:

  notification-manager:
    build:
      context: ../NotificationManager
      dockerfile: Dockerfile
    container_name: notification_manager
    environment:
      RABBITMQ_HOST: 192.168.25.3
      RABBITMQ_LOG_QUEUE: log_queue
      RABBITMQ_LOG_EXCHANGE: log_exchange
      RABBITMQ_LOG_KEY: log_routing_key
      RABBITMQ_USER: ing3
      RABBITMQ_PASS: paas
      REDIS_HOST: 192.168.25.4
      REDIS_PORT: 6379
      POSTGRES_HOST: 34.163.9.144
      POSTGRES_DB: domotik
      POSTGRES_USER: domotik
      POSTGRES_PASSWORD: episen2025ncc
      POSTGRES_PORT: 5432
    volumes:
      - ../NotificationManager:/app
    command: [ "poetry", "run", "python", "main.py" ]

  data-exchange:
    build:
      context: ../DataExchange
      dockerfile: Dockerfile
    container_name: data_exchange
    environment:
      MQTT_BROKER: 192.168.25.3
      MQTT_PORT: 1883
      MQTT_CONS_TOPIC: mqtt/log-topic
      MQTT_PROD_TOPIC: mqtt/config-topic
      MQTT_USER: exchange
      MQTT_PASS: toto
      RABBITMQ_HOST: 192.168.25.3
      RABBITMQ_CONF_EXCHANGE: config_exchange
      RABBITMQ_CONF_QUEUE: config_queue
      RABBITMQ_CONF_KEY: config_routing_key
      RABBITMQ_LOG_EXCHANGE: log_exchange
      RABBITMQ_LOG_QUEUE: log_queue
      RABBITMQ_LOG_KEY: log_routing_key
      RABBITMQ_USER: ing3
      RABBITMQ_PASS: paas
      MONGODB_HOST: 192.168.25.4
      MONGODB_PORT: 27017
      POSTGRES_HOST: 34.163.9.144
      POSTGRES_DB: domotik
      POSTGRES_USER: domotik
      POSTGRES_PASSWORD: episen2025ncc
      POSTGRES_PORT: 5432
    volumes:
      - ../DataExchange:/app
    command: [ "poetry", "run", "python", "main.py" ]
